### ISSUE TITLE
Can't add tags

### ISSUE THREAD

**Issue by rakeshp2007** [microcosm-cc/bluemonday#119]
Hi, How to enable following tags
1.DOCTYPE
2.meta
3.xml

Also following code gets removed
 &gt!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--&gt

So how to solve these issues ?

**Comment by buro9** [comment]
Do you have a test that shows what you expect given a piece of example
input?

Additionally do you realise that we use a HTML 5 parsing library and are
designed for user generated content? If so, what's your use case? What are
you trying to achieve?

**Comment by buro9** [comment]
I've no idea who you are... but emailing me, messaging on WhatsApp, calling me, all in addition to doing what you should be doing (engaging with the issue on Github) is unacceptable. I have a life, it's a Sunday morning, and this is not a severe security issue with this library.

Your use-case based on what you provided is unsupported. This library uses a HTML 5 lib to parse HTML and you appear to want to produce XHTML 1 (based on what you'd emailed me - derived from stripo.email tooling). Additionally you don't appear to have taken any time to solve your own problem, instead you've just hounded me across all my contact surfaces. You can take the code in this project and extend it trivially to allow comments (to support the addition of MS Outlook tags from the early 2000s) or other tags. The DocType you would need to manually prepend as the parsing lib explicitly is HTML 5 only.

I shall not engage with you further due to the way that you've hounded me across every contact surface.

**Comment by rakeshp2007** [comment]
Ok, David,

Thanks for the reply. Will not ping you in email and phone.
