### ISSUE TITLE
Turn disallowed tags into html entities

### ISSUE THREAD

**Issue by bigblind** [microcosm-cc/bluemonday#13]
It would be useful to have the option to turn stripped tags into entities instead of completely removing them. So

```
<script></script>
```

would be turned into

```
&lt;script&gt;&lt;/script&gt;

**Comment by buro9** [comment]
Why would you want this?

There is a risk that once you'vesaid it's not whitelisted and potentially unsafe, that letting it through in some mangled form allows an attacker to presume that their attack isn't removed but is merely transformed. This would allow an attacker to go after a later stage in the process, to take advantage of something else in a web page to try and get the transformed attack to work again.

I am worried that if we are just inserting a mode to help debugging that we would actually be weakening the primary purpose of this lib, to sanitise user input so that it can be safely used.

If all you are looking for is a mode to help with debugging I would be more inclined to add instructions on how to use a diff tool to show the difference before and after sanitisation.

I'd need a really strong answer to *why* to add this.
