### ISSUE TITLE
Add SVG+XML type support to the dataURIImagePrefix

### ISSUE THREAD

**Issue by EvgenMatiola99** [microcosm-cc/bluemonday#146]
I suggest to add also (...|**svg+xml**|...) type to the **dataURIImagePrefix** because it can be useful in some cases
![image](https://user-images.githubusercontent.com/30429547/168083061-5f0e2e67-6030-4486-a0b6-2a32a53fac33.png)
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#discrete_types](url)
![image](https://user-images.githubusercontent.com/30429547/168086206-68b0e40a-b6c7-45a0-8a7d-077a01f8bed3.png)
Thanks a lot.

**Comment by buro9** [comment]
I'm happy to do this and will add it now.

https://digi.ninja/blog/svg_xss.php clearly shows that so long as `image/svg+xml` is accessed through image tags that there is no execution of containing script whilst the SVG is displayed inline rather than accessed directly.

However... if proof emerges that this is in fact not true I'll revisit this.
