### ISSUE TITLE
Option to add spaces

### ISSUE THREAD

**Issue by jonathan-wondereur** [microcosm-cc/bluemonday#188]
When stripping HTML tags, you can sometimes combine words without spaces, making it hard to understand. I want to add a space every time you remove a tag.

Right now:
```
p := bluemonday.StrictPolicy()
p.Sanitize('<div>This is great</div><div>i know</div>')
```

Results in: `This is greati know`

I would like it to result in: `This is great i know` or `This is great  i know`

**Comment by buro9** [comment]
This isn't the job of this package which is designed to create safe output from untrusted input, so I'm going to decline this idea.

HTML is not whitespace sensitive, and the display properties of HTML elements come from the elements, the removal of such elements removes any presentation hints... but this is by design.

That said, you could trivially achieve what you want by pre-parsing the input such that any `><` is replaced by `> <`, so I would recommend that in this instance.

**Comment by jonathan-wondereur** [comment]
Okay, thanks, I decided to prettify the HTML first using: https://github.com/yosssi/gohtml

`><` to `> <` will cover most cases but not the case of `...<p>some text<strong>is important</strong>and others is not` in this case it would result in `some textis importantand others is not`, joining together some words when the HTML is stripped out of the text making it unreadable.
