### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by psikoz** [microcosm-cc/bluemonday#70]
Hey @buro9 . I desinged a logo for you. I put the initials of the project together and I chose a blue color. WDYT? Please tell me your thoughts.

![bm](https://user-images.githubusercontent.com/40601249/42757194-bbd8beaa-8907-11e8-9958-4bb08db03478.jpg)

**Comment by buro9** [comment]
Hi,

This is good work and I do like it. However I am not sure it is needed and separately am kinda against it because the name was chosen flippantly and I have been considering renaming it to just "Go HTML5 Sanitizer" with a package name of "sanitizer".

I'm still thinking about that rename, but even if done am not convinced this package, or any utility package, really needs a logo.

The effort is appreciated though.
